# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zYbhzKQ41KEri7sC7e30XgSZ-50sQ37l
"""

text = "Data Science python"
print (text.split())
print(text.split("e",1))
print(text.split("a",1))

name = "MONKEY D LUFFY"
dream = "the king of the jangle"
print(f"my name is {name} my dream is {dream}")

s[0]="h"

s="arun"
t="h"+ s[:]
print(t)

text='a v e n g e r s d o o m s d a y'
 stripped_text=text.strip
 no_space_text=text.replace(" ","")
 print(f"'{no_space_text}'")

